# Generated by Django 3.1 on 2020-09-07 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.DecimalField(decimal_places=10, default='DEFAULT VALUE', max_digits=20),
        ),
    ]
