# Generated by Django 3.1 on 2020-09-07 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_cart_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
    ]
